/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.*;
import DTO.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MI
 */
public class BChucVu extends javax.swing.JPanel {

    /**
     * Creates new form BChucVu
     */
        ChucVuBUS chucvubus;
    ChucVuDTO chucvudto;
    NhanvienBUS nhanvienbus;
    DefaultTableModel defaultTableModel;
    public BChucVu() 
    {
        initComponents();
        chucvubus = new ChucVuBUS();
        chucvudto = new ChucVuDTO();
        nhanvienbus = new NhanvienBUS();
        setdatacombo();
        defaultTableModel = new DefaultTableModel()
                {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
                    
                };
        tablechucvu.setModel(defaultTableModel);
        defaultTableModel.addColumn("Mã Nhân Viên");
        defaultTableModel.addColumn("Tên Nhân Viên");
        defaultTableModel.addColumn("Mã Chức Vụ");
        defaultTableModel.addColumn("Tên Chức Vụ");
        defaultTableModel.addColumn("Ngày Bổ Nhiệm ");
        defaultTableModel.addColumn("Chi Chú");
        setChucvudata(chucvubus.getChucvu());
    
        tablechucvu.addMouseListener(new MouseAdapter()
        {
                public void mouseClicked(MouseEvent e) 
        {
                int row = tablechucvu.getSelectedRow();
                if (row >= 0) 
                {
                    
                    String MaNv = "";
                    String TenNv = "";
                    String MaCv = "";
                    String TenCv = "";
                    String Ngaybnh = "";
                    String ghichu = "";
                    DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

                    if (tablechucvu.getValueAt(row, 0) != null) {
                        MaNv = tablechucvu.getValueAt(row, 0).toString();
                    }
                    if (tablechucvu.getValueAt(row, 1) != null) {
                        TenNv = tablechucvu.getValueAt(row, 1).toString();
                    }
                    if (tablechucvu.getValueAt(row, 2) != null) {
                        MaCv = tablechucvu.getValueAt(row, 2).toString();
                    }
                    if (tablechucvu.getValueAt(row, 3) != null) {
                        TenCv = tablechucvu.getValueAt(row, 3).toString();
                    }
                    Object ngaybnhObj = tablechucvu.getValueAt(row, 4);
                if (ngaybnhObj != null) {
                    Ngaybnh = dateFormat.format((Date) ngaybnhObj);
                }
                    if (tablechucvu.getValueAt(row, 5) != null) {
                        ghichu = tablechucvu.getValueAt(row, 5).toString();
                    }

                    manvbox.setSelectedItem(MaNv);
                    tennvbox.setSelectedItem(TenNv);
                    ngaybnhf.setText(Ngaybnh);
                    macvf.setText(MaCv);
                    tencvf.setText(TenCv);
                   // ghichuf.setText(ghichu);
                }
            }

            });
    }
    public void setChucvudata(ArrayList<ChucVuDTO> chucvulist)
     {
            for (ChucVuDTO chucvu : chucvulist) {
                defaultTableModel.addRow(new Object[]{
                    chucvu.getMaNvcv(),
                    chucvu.getTenNvcv(),
                    chucvu.getMaCv(),
                    chucvu.getTenCv(),
                    chucvu.getNgaybonhiem(),
                    chucvu.getGhichu()
                      
                });
            }


    }
        public  void setdatacombo()
            
    {
        manvbox.removeAllItems();
        tennvbox.removeAllItems();;
        ArrayList<NhanvienDTO> nvlist = new ArrayList();
        nvlist = nhanvienbus.getNhanvien();
        for (NhanvienDTO nv : nvlist )
        {
            manvbox.addItem(nv.getMaNv());
            tennvbox.addItem(nv.getTenNv());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BangPhongban = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        ngaybnhf = new javax.swing.JTextField();
        Deletebt = new javax.swing.JButton();
        Savebt = new javax.swing.JButton();
        Thembt = new javax.swing.JButton();
        TimKiembt = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablechucvu = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        macvf = new javax.swing.JTextField();
        manvbox = new javax.swing.JComboBox<>();
        tennvbox = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        tencvf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        BangPhongban.setBackground(new java.awt.Color(255, 255, 255));
        BangPhongban.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BangPhongban.setToolTipText("");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("CHỨC VỤ");
        jLabel23.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Mã Nhân Viên");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Tên Nhân Viên");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Ngày Bổ Nhiệm ");

        ngaybnhf.setBackground(new java.awt.Color(255, 255, 255));
        ngaybnhf.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        ngaybnhf.setForeground(new java.awt.Color(0, 0, 0));
        ngaybnhf.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ngaybnhf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngaybnhfActionPerformed(evt);
            }
        });

        Deletebt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Deletebt.setForeground(new java.awt.Color(255, 0, 0));
        Deletebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebtActionPerformed(evt);
            }
        });

        Savebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavebtActionPerformed(evt);
            }
        });

        Thembt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Thembt.setForeground(new java.awt.Color(255, 51, 51));
        Thembt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThembtActionPerformed(evt);
            }
        });

        TimKiembt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiembtActionPerformed(evt);
            }
        });

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 0, 51));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Thêm");

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 0, 0));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Sửa");

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 0, 0));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Lưu");

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 0, 0));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Xóa");

        tablechucvu.setAutoCreateRowSorter(true);
        tablechucvu.setBackground(new java.awt.Color(255, 255, 255));
        tablechucvu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablechucvu.setForeground(new java.awt.Color(0, 0, 0));
        tablechucvu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Phòng Ban", "Tên Phòng Ban", "Số Điện Thoại", "Số Nhân Viên"
            }
        ));
        tablechucvu.setRowHeight(30);
        tablechucvu.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(tablechucvu);

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Mã Chức Vụ");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Ghi Chú");

        macvf.setBackground(new java.awt.Color(255, 255, 255));
        macvf.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        macvf.setForeground(new java.awt.Color(0, 0, 0));
        macvf.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        manvbox.setBackground(new java.awt.Color(255, 255, 255));
        manvbox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        manvbox.setForeground(new java.awt.Color(0, 0, 0));
        manvbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tennvbox.setBackground(new java.awt.Color(255, 255, 255));
        tennvbox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tennvbox.setForeground(new java.awt.Color(0, 0, 0));
        tennvbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Tên Chức Vụ");

        tencvf.setBackground(new java.awt.Color(255, 255, 255));
        tencvf.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tencvf.setForeground(new java.awt.Color(0, 0, 0));
        tencvf.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(17);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(3);
        jTextArea1.setTabSize(6);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout BangPhongbanLayout = new javax.swing.GroupLayout(BangPhongban);
        BangPhongban.setLayout(BangPhongbanLayout);
        BangPhongbanLayout.setHorizontalGroup(
            BangPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BangPhongbanLayout.createSequentialGroup()
                .addGroup(BangPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BangPhongbanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5))
                    .addGroup(BangPhongbanLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(BangPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(BangPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BangPhongbanLayout.createSequentialGroup()
                                .addGap(382, 382, 382)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(554, 554, 554))
                            .addGroup(BangPhongbanLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(BangPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ngaybnhf)
                                    .addComponent(manvbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tennvbox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 212, Short.MAX_VALUE))
                                .addGap(58, 58, 58)
                                .addGroup(BangPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BangPhongbanLayout.createSequentialGroup()
                                        .addGroup(BangPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(BangPhongbanLayout.createSequentialGroup()
                                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                                .addComponent(Thembt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(BangPhongbanLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(BangPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Savebt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(BangPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(BangPhongbanLayout.createSequentialGroup()
                                                .addComponent(TimKiembt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Deletebt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(BangPhongbanLayout.createSequentialGroup()
                                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE))
                                    .addGroup(BangPhongbanLayout.createSequentialGroup()
                                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(macvf, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(BangPhongbanLayout.createSequentialGroup()
                                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tencvf, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        BangPhongbanLayout.setVerticalGroup(
            BangPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BangPhongbanLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(BangPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BangPhongbanLayout.createSequentialGroup()
                        .addGroup(BangPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manvbox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BangPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(macvf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BangPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tennvbox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tencvf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BangPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BangPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ngaybnhf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(Savebt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Thembt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimKiembt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Deletebt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BangPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1281, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(BangPhongban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(BangPhongban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ngaybnhfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngaybnhfActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ngaybnhfActionPerformed

    private void DeletebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebtActionPerformed
        
    }//GEN-LAST:event_DeletebtActionPerformed

    private void SavebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavebtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SavebtActionPerformed

    private void ThembtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThembtActionPerformed
        

    }//GEN-LAST:event_ThembtActionPerformed

    private void TimKiembtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiembtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimKiembtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BangPhongban;
    private javax.swing.JButton Deletebt;
    private javax.swing.JButton Savebt;
    private javax.swing.JButton Thembt;
    private javax.swing.JButton TimKiembt;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField macvf;
    private javax.swing.JComboBox<String> manvbox;
    private javax.swing.JTextField ngaybnhf;
    private javax.swing.JTable tablechucvu;
    private javax.swing.JTextField tencvf;
    private javax.swing.JComboBox<String> tennvbox;
    // End of variables declaration//GEN-END:variables
}
